LineLength:
  Enabled: false

MethodLength:
  Max: 30

SymbolName:
  AllowCamelCase: false

Documentation:
  Enabled: false

AllCops:
  Excludes:
    - lib_old/**
    - spec/unit/lib_old/**
    - spec/integration/lib_old/**
